#!/bin/bash
#encode with ffmpeg 
function ffenc(){
target=$1
in="$2"
out=$3
FFMPEG=$(which ffmpeg)
if [ $# -ne 3 ]
    then echo "wrong number of arguments!"
    return
fi

case $target in 
        4droid) 
                $FFMPEG -i "$in" \
                -vcodec h264 \
                -preset faster \
                -profile baseline \
                -crf 25 \
                -s 854x480 \
                -acodec libfdk_aac \
                -async 1 \
                -ab 128k \
                -n \
                $out
                ;;
        4dvdstyler)
                $FFMPEG -i "$in" \
                -target pal-dvd \
                -ac 2 \
                -ab 192k \
                -aspect 16:9 \
                -b:v 4000k \
                $out
                ;;
esac
}
