#!/bin/bash
. ~/.bash/functions.d/log

for file in ~/.bash/variables.d/*; 
  do 
    log "loading $file"
    . $file
done


export ANDROID_SDK=/opt/android/sdk
export ANDROID_NDK=/opt/android-ndk-r7b
export BB_HOME=/opt/blackberry
export BB_SDK=$BB_HOME/tools/SDK
export ECLIPSE_HOME=~/.eclipse/

export EDITOR=vim

#########################################
#Diploma Thesis
export MATLABPATH=~/matlab


#########################################


SCRIPT_DIR=~/Dropbox/unencrypted/Programmierung\ und\ Programme/Skripte
export PATH=$PATH:/usr/sbin
export PATH=$PATH:/sbin
export PATH=$PATH:~/bin
#Android stuff
export PATH=$PATH:$ANDROID_SDK/platform-tools
export PATH=$PATH:$ANDROID_SDK/tools
export PATH=$PATH:$ANDROID_NDK
export PATH=$PATH:$BB_SDK/bin

export HEALTHMANAGER=$HOME/git/biocomfort/healthmanager
export thesis=$HOME/workspace/Studienarbeit/bachelor-thesis

# ROS
export ROS_VMI_SVN=~/workspace/Forschungspraxis/vmi-ros-pkg
export ROS_VMI_ROALTER_BRANCH=$ROS_VMI_SVN/branch/0.4-roalter
export ROS_VMI_COGNITIVE_LOCATIONS=$ROS_VMI_SVN/trunk/vmi_cognitive_environment:$ROS_VMI_ROALTER_BRANCH/vmi_cognitive_environment:$ROS_VMI_ROALTER_BRANCH/vmi_external_dependencies
export ROS_WORKSPACE=~/workspace/ros/packages
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$ROS_VMI_COGNITIVE_LOCATIONS:$ROS_WORKSPACE

export EXTERNAL_DISK_256GB=/media/andreas/9580b6e2-65f4-4e1f-aba4-468eef03b95a
export Z=$EXTERNAL_DISK_256GB
export WF=$Z/Privat/Fussball/Weihnachtsfeier/2012

export PYTHONPATH=$PYTHONPATH:/usr/lib/gimp/2.0/python/

export BBTH="$EXTERNAL_DISK_256GB/Video/Serien/Big-Bang-Theory"
export SPD="$EXTERNAL_DISK_256GB/Video/Serien/Southpark"

export HS=~/Dropbox/unencrypted/Studium/Hauptseminar

export FFMPEG_DATADIR=~/.ffmpeg/
export OCTAVE_HOME=~/Dropbox/unencrypted/Programmieren/octave/
export PAGER=vimpager
export S=/media/andreas/F4AD-DCDC/

# latex include
export TEXMFHOME=~/.texmf

# tuxonice
export SLEEP_MODULE=kernel

# xilinx ise webpack location
#export XILINX_HOME=~/opt/14.5/ISE_DS
#source $XILINX_HOME/settings64.sh
#export GRLIB=~/da/grlib


#wine
WINEPREFIX=/home/andreas/.wine

export OPT=~/opt

export BASH_LOG=~/.bash_log
