#!/bin/bash
. ~/.bash/functions.d/path

# EDITOR
export EDITOR=vim
export PAGER=less

# PATH
updatepath ~/homebrew/bin
updatepath /usr/sbin
updatepath /sbin
updatepath ~/bin
updatepath ~/sbin
updatepath ~/.bash/scripts.d
updatepath /usr/local/go/bin
updatepath /usr/local/share/jruby/bin
updatepath /opt/gradle/bin
updatepath ~/cpos/apps/connector-apps-libs-python/connector/scripts

# PYTHONPATH
export PYTHONPATH=.

UNAME=$(uname)
DISTRIBUTION=$(lsb_release >/dev/null 2>&1 && lsb_release -si)

for file in ~/.bash/variables.d/*; 
do 
  log "loading $file"
  . $file
done
