#!/bin/bash
. ~/.bash/functions.d/path

export EDITOR=vim
export PAGER=less

updatepath ~/homebrew/bin
updatepath /usr/sbin
updatepath /sbin
updatepath ~/bin
updatepath ~/sbin
updatepath ~/.bash/scripts.d
updatepath /usr/local/go/bin
updatepath /usr/local/share/jruby/bin
updatepath /opt/gradle/bin

UNAME=$(uname)
DISTRIBUTION=$(lsb_release >/dev/null 2>&1 && lsb_release -si)

for file in ~/.bash/variables.d/*; 
do 
  log "loading $file"
  . $file
done
