#!/bin/bash

export PYTHONPATH=$PYTHONPATH:~/dev/:~/git/:~

function docker(){
DOCKER=/usr/bin/docker
if [[ $1 == "ips" ]]; then
  for CID in $(${DOCKER} ps -q); do echo "$CID $(${DOCKER} inspect --format '{{ .NetworkSettings.IPAddress }}' $CID)";done
elif [[ $1 == "ip" && -n $2 ]]; then
  CID=$2
  echo "$(${DOCKER} inspect --format '{{ .NetworkSettings.IPAddress }}' $CID)"
else
  $DOCKER $*
fi
}

export CDPATH=$CDPATH:~/cpos/analytics/analytics
export CDPATH=$CDPATH:~/cpos/
