#!/bin/bash
. ~/.bash/functions.d/path

case $UNAME in 
  Linux)
    ANDROID_SDK=/opt/android/sdk
    ;;
  Darwin)
    ANDROID_SDK=~/Library/Android/sdk
    ;;
  *)
    return
    ;;
esac


#Adjust path
updatepath $ANDROID_SDK/platform-tools
updatepath $ANDROID_SDK/tools
