#!/bin/bash

export ANDROID_SDK=$OPT/android/sdk
export ANDROID_NDK=$OPT/android-ndk-r7b

export ANDROID_SEARCH_API=19
export ANDROID_HOME=$ANDROID_SDK # used in vim-android

#Adjust path
export PATH=$PATH:$ANDROID_SDK/platform-tools
export PATH=$PATH:$ANDROID_SDK/tools
export PATH=$PATH:$ANDROID_NDK
export PATH=$PATH:$BB_SDK/bin
