#!/bin/bash

if [[ $UNAME == 'Darwin' ]]; then
  #export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home
  export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home
elif [[ $UNAME == 'Linux' && $DISTRIBUTION == 'CentOS' ]]; then
  export JAVA_HOME=/usr/java/default
fi

export JDK_HOME=$JAVA_HOME
export JRE_HOME=$JDK_HOME/jre
