#!/bin/bash

case $UNAME in 
  Linux)
    ;;
  Darwin)
    export JYTHON_HOME="$HOME/homebrew/Cellar/jython/2.7.0/libexec/"
    ;;
  *)
    return
    ;;
esac

JYTHONPATH=$JYTHONPATH:~/git/
JYTHONPATH=$JYTHONPATH:~/lib/python2.7/site-packages/
export JYTHONPATH
