#!/bin/bash


case $UNAME in 
  Linux)
    ;;
  Darwin)
	  PYTHONPATH=$PYTHONPATH:~/lib/python2.7/site-packages
    PYTHONPATH=$PYTHONPATH:~/homebrew/lib/python2.7/site-packages
		PYTHONPATH=$PYTHONPATH:~/homebrew/Cellar/python/2.7.11/libexec/pip
    ;;
  *)
    return
    ;;
esac
