#!/bin/bash

export PYTHONPATH=./packages/
export PYTHONPATH=$PYTHONPATH:~/dev/python/

case $UNAME in 
  Linux)
    ;;
  Darwin)
    PYTHONPATH=$PYTHONPATH:~/lib/python2.7/site-packages
    ;;
  *)
    return
    ;;
esac
